### ISSUE TITLE
Possible issue with deployment templating

### ISSUE THREAD

**Issue by sj-williams** [wcarlsen/aws-subnet-exporter#1]
Hi @wcarlsen thank you for putting this service together - i'm keen to make use of!

Having played around with it a little, I'm encountering an issue whereby the service fails to connect to the AWS EC2 API. The pod goes into crashloop with log:

```
{"level":"fatal","msg":"cannot describe subnets: operation error EC2: DescribeSubnets, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://sts.\\\"eu-west-2\\\".amazonaws.com/\": dial tcp: lookup sts.\"eu-west-2\".amazonaws.com: no such host","time":""}
```

I can fix this by doing a `kubectl edit deploy` and removing the quotes around the `args`:

```
spec:
  containers:
  - args:
    - --region="eu-west-2"
    - --filter="*"
    - --port=8080
```
becomes
```
spec:
  containers:
  - args:
    - --region=eu-west-2
    - --filter=*
    - --port=8080
```
(this also is required to get the filter working on subnets)

Might I suggest removing the quotes in the [deployment template](https://github.com/wcarlsen/aws-subnet-exporter/blob/main/charts/aws-subnet-exporter/templates/deployment.yaml#L35-L45)? Happy to raise a PR if you'd like.

For information, I'm deploying via Terraform with Hashicorp Helm provider.

Many thanks again!
